### PR TITLE
Make Cache Monster usable as a git submodule

### PR DESCRIPTION
**Pull request by davissorenson**
I like to use git submodules for Craft plugins, to keep our history clean and make keeping up to date with upstream easy.

Sorry for changing your entire directory structure in the first pull request.

### CODE REVIEW

**Comment by joshangell** [comment]
Hi Davis, thanks for the PR!

Sorry but this time I'm not going to do this - one of the things with Craft is that you have to have the folder name correct when you add a plugin to the `/craft/plugins` directory and moving the actual plugin contents up a level just introduces more installation errors as people have to make the folder themselves.

So for ease of use for the less tech-savvy user I always use the current structure. I appreciate the audience for this particular plugin is probably pretty tech literate but I don’t want to assume that and also don’t want one of my plugins to be different in structure to the others.

Hopefully that explains the method to my madness ...

Josh

**Comment by davissorenson** [comment]
Totally understandable, thanks for taking the time to review this.

**Comment by joshangell** [comment]
No problem - sorry if it interrupts your workflow!

**Comment by davissorenson** [comment]
Nope! I forked it into the organization of the agency I work for, I'll just rebase every time we update. It will most likely be in use on a high-traffic site, so we won't be updating Cache Monster without double checking everything anyway.

**Comment by joshangell** [comment]
Ha yes - same model we use :) let me know if / when you use it, I'd be interested in the results.

**Pull request closed without merging**
